### PR TITLE
Add XMM RGS spectra

### PR DESCRIPTION
**Pull request by hamogu**
XMM is, besides Chandra, the other major X-ray mission, and besides Chandra the other mission with grating spectroscopy. I think we really do need XMM/RGS data for our testing, because they do a few things differently compared to Chandra and testing grating data is really underrepresented in our tests anyway.

I acknowledge that these files are big, but unfortunately, that's the way it is. 
PRs that makes use of them are coming.

# Data description
XMM/RGS data with background and ARF/RMF. The source is a stellar source, so for modeling tests a model like "xsphabs * (vapec.v1 + vapec.v2)" would be appropriate. The source spectrum is strong enough to fit OK, but not so strong that the background is negligible.

### CODE REVIEW

**Review by DougBurke — APPROVED** [review]
I think it makes sense to add these - I've been trying to expand our test coverage to include the current set of "interesting" missions and the XMM RGS case is one we definitely want to support.

**Comment by DougBurke** [comment]
@Marie-Terrell I guess you need official sign off on this (I don't think we've ever really discussed the process for sherpa-test as it is not changed often)?

**Comment by hamogu** [comment]
In the meeting today we discussed the structure of this repository. I looked back at #7 and https://github.com/sherpa/sherpa/pull/164 where the directory structure was flattened, but it is not clear *why* that was done. I, in fact, find the current, flat directory structure hard to read. It is often not clear from the filename alone what type of data I'm looking at here (e.g. grating data, which mission). Of course, that's all part if the fits metadata and I *could* pierce that together, but I see no downside (nor is one spelled out in the issues referenced above) of grouping data that belong together (PHA, ARF, RMF) in one directory with a short, descriptive name. In order to re-use this data for multiple purposes (IO tests, plotting tests, examples in the docs) it's helpful to know what we are looking at.

So, I stand by putting the data files added in this PR into its own subdirectory.

However, I will also edit the top item in this PR with a short description of the data to help people in the future when they try to find out what this data is.

**Comment by olaurino** [comment]
> the directory structure was flattened, but it is not clear why that was done. I, in fact, find the current, flat directory structure hard to read

It was done because the original structure was highly redundant, with the same file repeated over and over in different folders belonging to different tests. We did a lot of work to reduce redundancy and streamline the way the test data is accessed, which went beyond flattening the test data. Maybe it would be easier now to restructure the folders in a rational way, although IIRC there are still tests that expect certain scripts with certain names to be in the same folder with the input data, so in the end that might be the limiting factor.

**Comment by hamogu** [comment]
Thanks @olaurino I agree we don't want duplication of test files and we also don't want a structure such as "IOtests/fits/abcd.arf" which makes it hard to reuse files (I guess that might have been the old structure?).

I also don't want to spend a lot of effort into changing this again. We did it once, it works, and we have more than enough things that are higher priority.
*My suggestion would be to apply the following to new files and new files only: If a test adds a few (say more than 2) files that belong together (in the sense that they are generated from the same observation, e.g. data, arf, rmf, background spectrum, background arf, ...), we put them in a subdirectory (no more than one level deep) with a name that describes the type (e.g. "XMMRGS" or "XMM_grating", so I know it's grating data from a non-Chandra instrument), and maybe even a short (5 lines, free form text) readme.*

That way, I can still use the same type of data for IO tests, fitting a model, or plotting, but I can easily see what type of data is being tested, while files like "data1.pi" or "source.arf" don't tell me if I'm looking at CCD spectra, grating data, Chandra, NuStar or whatever. That's a problem because I don't know (without reading the fits headers in each file), if e.g. IO or plotting is ever tested on grating data at all.

**Pull request merged**
